//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch rsrc.rc
//
#define MAX_LUA_OPEN_AND_RUN_INSTANCES  100
#define MIN_WINDOW_H                    100
#define MIN_WINDOW_W                    100
#define IDR_MYMENU                      101
#define IDM_SETTINGS                    105
#define IDD_SEEKER                      107
#define IDD_MAIN                        128
#define IDM_LOAD_ROM                    129
#define IDC_INTERP                      130
#define IDC_RECOMP                      131
#define IDC_PURE_INTERP                 132
#define IDB_LOGO                        133
#define IDC_LOGO                        134
#define IDC_COMBO_GFX                   135
#define IDM_VIDEO_SETTINGS              136
#define IDGFXTEST                       137
#define IDGFXABOUT                      138
#define IDC_COMBO_INPUT                 139
#define IDM_INPUT_SETTINGS              140
#define IDINPUTTEST                     141
#define IDINPUTABOUT                    142
#define IDC_CPUCORE                     143
#define IDC_GFXPLUGIN                   144
#define IDC_INPUTPLUGIN                 145
#define IDC_SOUNDPLUGIN                 146
#define IDI_M64ICONBIG                  147
#define IDI_AUSTRALIA                   148
#define IDI_USA                         149
#define IDI_JAPAN                       150
#define IDI_GERMANY                     151
#define IDI_EUROPE                      152
#define IDI_N64CART                     153
#define IDI_ITALIA                      154
#define IDI_SPAIN                       155
#define IDI_FRANCE                      156
#define IDI_UNKNOWN                     157
#define IDI_DEMO                        158
#define IDI_BETA                        159
#define IDM_ABOUT                       161
#define ID_HELP_CONTENS                 162
#define IDM_RAMSTART                    163
#define IDC_COMBO_SOUND                 164
#define IDM_AUDIO_SETTINGS              165
#define IDSOUNDTEST                     166
#define IDSOUNDABOUT                    167
#define IDB_UP_ARROW                    168
#define IDB_DOWN_ARROW                  169
#define IDI_SIF                         170
#define IDI_M64ICONSMALL                180
#define IDD_LUAWINDOW                   182
#define IDD_LUAINPUTPROMPT              183
#define IDC_WEBSITE                     190
#define IDC_COMBO_RSP                   200
#define IDM_RSP_SETTINGS                201
#define IDC_RSPPLUGIN                   202
#define IDRSPTEST                       203
#define IDRSPABOUT                      204
#define IDC_MAIN_STATUS                 1002
#define IDC_PLUGIN_DEFAULT              1003
#define IDC_SKIPFREQUENCY_HELP          1003
#define IDD_DIRECTORIES                 1004
#define IDC_ROMBROWSER_DIR_LIST         1006
#define IDC_ADD_BROWSER_DIR             1007
#define IDC_REMOVE_BROWSER_DIR          1008
#define IDC_REMOVE_BROWSER_ALL          1009
#define IDC_ROMS_DIRECTORIES            1010
#define IDC_RECURSION                   1011
#define IDM_STATUSBAR                   1013
#define IDC_PLUGIN_DIRECTORY_HELP       1014
#define IDC_HOTKEY_LIST                 1015
#define IDC_HOTKEY_ASSIGN_SELECTED      1016
#define IDC_SELECTED_HOTKEY_TEXT        1017
#define IDC_HOTKEY_SEARCH               1018
#define IDC_HOTKEY_CLEAR                1019
#define IDC_LIST1                       1019
#define IDC_COREDBG_LIST                1019
#define IDD_ABOUT                       1020
#define IDC_USESUMMERCART               1021
#define IDC_CAPTUREOTHER                1022
#define IDC_CAPTUREDELAY                1026
#define IDC_RADIO_FROM_START            1027
#define IDC_RADIO_FROM_ST               1028
#define IDC_RADIO_FROM_EEPROM           1029
#define IDC_RADIO_FROM_EXISTING_ST      1030
#define IDC_PAUSE_AT_END                1031
#define IDC_RADIO1                      1033
#define IDC_EDIT1                       1035
#define IDC_SEEKER_FRAME                1035
#define IDC_MOVIE_INFO_TEMPLATE         1036
#define IDM_FULLSCREEN                  1061
#define IDM_PAUSE                       1062
#define IDM_FRAMEADVANCE                1063
#define EMU_PLAY                        1064
#define IDM_CLOSE_ROM                   1065
#define IDM_REFRESH_ROMBROWSER          1066
#define IDM_VCR_READONLY                1067
#define REPLACEDLGORD                   1541
#define RUNDLGORD                       1545
#define IDC_MANAGE_LINK                 1592
#define ID_POPUP_ROM_SETTING            2000
#define IDD_ROM_SETTING_DIALOG          2001
#define IDC_OK                          2003
#define IDC_CANCEL                      2004
#define IDC_ROM_CRC1                    2006
#define IDC_ROM_CRC2                    2007
#define IDC_ROM_HEADER_INFO_TEXT        2008
#define IDC_ROM_FULLPATH_TEXT           2009
#define IDC_ROM_FULLPATH                2010
#define IDC_ROM_GOODNAME_TEXT           2011
#define IDC_ROM_GOODNAME                2012
#define IDC_ROM_INTERNAL_NAME_TEXT      2013
#define IDC_ROM_INTERNAL_NAME           2014
#define IDC_ROM_CRC1_TEXT               2015
#define IDC_ROM_CRC2_TEXT               2016
#define IDC_ROM_COUNTRY_TEXT            2017
#define IDC_ROM_COUNTRY                 2018
#define IDC_INI_COMMENTS_TEXT           2019
#define IDC_INI_COMMENTS                2020
#define IDC_ROM_MD5_TEXT                2021
#define IDC_ROM_MD5                     2022
#define IDC_MD5_CALCULATE               2023
#define IDC_MD5_PROGRESS                2024
#define IDC_ROM_SIZE_TEXT               2025
#define IDC_ROM_SIZE                    2026
#define IDC_ROM_INICODE_TEXT            2027
#define IDC_ROM_INICODE                 2028
#define IDC_MD5_PROGRESS_BAR            2029
#define ID_START_ROM                    2050
#define ID_START_ROM_ENTER              2051
#define ID_AUDIT_ROMS                   2100
#define IDD_AUDIT_ROMS_DIALOG           2101
#define IDC_AUDIT_STOP                  2102
#define IDC_AUDIT_CLOSE                 2103
#define IDC_AUDIT_START                 2104
#define IDC_TOTAL_ROMS_TEXT             2105
#define IDC_TOTAL_ROMS                  2106
#define IDC_CURRENT_ROM_TEXT            2107
#define IDC_CURRENT_ROM                 2108
#define ID_GENERATE_ROM_INFO            2200
#define IDD_MESSAGES                    2250
#define IDC_MESSAGES                    2255
#define IDC_LIMITFPS                    2257
#define IDC_FPSTITLE                    2258
#define IDC_FPSTRACKBAR                 2259
#define IDC_FPSTITLE2                   2259
#define IDC_SPEEDMODIFIER_VALUE         2261
#define IDC_INCREASE_MODIFIER           2262
#define IDC_DECREASE_MODIFIER           2263
#define IDC_RESET_MODIFIER              2264
#define IDC_SKIPFREQ                    2265
#define IDC_0INDEX                      2266
#define IDC_FASTFORWARDSKIPFREQ         2268
#define IDM_SAVE_SLOT                   3000
#define IDM_SAVE_STATE_AS               3001
#define IDM_LOAD_SLOT                   3002
#define IDM_LOAD_STATE_AS               3003
#define ID_CURRENTSAVE_DEFAULT          3004
#define IDM_SELECT_1                    3005
#define IDM_SELECT_2                    3006
#define IDM_SELECT_3                    3007
#define IDM_SELECT_4                    3008
#define IDM_SELECT_5                    3009
#define IDM_SELECT_6                    3010
#define IDM_SELECT_7                    3011
#define IDM_SELECT_8                    3012
#define IDM_SELECT_9                    3013
#define IDM_SELECT_10                   3014
#define ID_SAVE_1                       3015
#define ID_SAVE_2                       3016
#define ID_SAVE_3                       3017
#define ID_SAVE_4                       3018
#define ID_SAVE_5                       3019
#define ID_SAVE_6                       3020
#define ID_SAVE_7                       3021
#define ID_SAVE_8                       3022
#define ID_SAVE_9                       3023
#define ID_SAVE_10                      3024
#define ID_LOAD_1                       3025
#define ID_LOAD_2                       3026
#define ID_LOAD_3                       3027
#define ID_LOAD_4                       3028
#define ID_LOAD_5                       3029
#define ID_LOAD_6                       3030
#define ID_LOAD_7                       3031
#define ID_LOAD_8                       3032
#define ID_LOAD_9                       3033
#define ID_LOAD_10                      3034
#define IDC_DEFAULT_PLUGINS_CHECK       4000
#define IDC_DEFAULT_SCREENSHOTS_CHECK   4001
#define IDC_DEFAULT_SAVES_CHECK         4002
#define IDC_DEFAULT_PLUGINS_DIR         4003
#define IDC_DEFAULT_SAVES_DIR           4004
#define IDC_DEFAULT_SCREENSHOTS_DIR     4005
#define IDC_PLUGINS_GROUP               4012
#define IDC_SAVES_GROUP                 4013
#define IDC_SCREENSHOTS_GROUP           4014
#define IDC_PLUGINS_DIR                 4015
#define IDC_CHOOSE_PLUGINS_DIR          4016
#define IDC_SCREENSHOTS_DIR             4017
#define IDC_CHOOSE_SCREENSHOTS_DIR      4018
#define IDI_GFX                         4101
#define IDI_INPUT                       4103
#define IDI_SOUND                       4104
#define IDB_RSP                         4112
#define IDB_SOUND                       4113
#define IDB_CONTROL                     4114
#define IDB_DISPLAY                     4115
#define ROM_POPUP_MENU                  4116
#define IDC_CURRENT_ROM_PROGRESS        5001
#define IDC_TOTAL_ROMS_PROGRESS         5002
#define IDC_SAVES_DIR                   5004
#define IDC_IDC_ROM_MD5                 5011
#define IDC_CHOOSE_SAVES_DIR            5014
#define IDM_SCREENSHOT                  5015
#define IDC_PAUSENOTACTIVE              5503
#define IDC_ROMBROWSERCOLUMNS           5504
#define IDC_STATUSBAR                   5504
#define IDC_COLUMN_GOODNAME             5505
#define IDC_AUTOINCREMENTSAVESLOT       5505
#define IDC_COLUMN_INTERNALNAME         5506
#define IDC_COLUMN_COUNTRY              5507
#define IDC_COLUMN_SIZE                 5508
#define IDC_COLUMN_FILENAME             5509
#define IDC_COLUMN_MD5                  5510
#define IDC_COLUMN_COMMENTS             5511
#define IDC_COMMON                      5513
#define IDC_COMPATIBILITY               5514
#define IDC_ENABLE_AUDIO_DELAY          5515
#define IDC_ENABLE_COMPILED_JUMP        5516
#define IDD_HOTKEY_CONFIG               5518
#define IDC_WARNING_OPTIONS             5519
#define IDM_RESET_RECENT_ROMS           6000
#define IDM_FREEZE_RECENT_ROMS          6001
#define ID_RECENTROMS_FIRST             6002
#define IDM_RESET_RECENT_MOVIES         6020
#define IDM_FREEZE_RECENT_MOVIES        6021
#define ID_RECENTMOVIES_FIRST           6022
#define IDM_LOAD_LUA                    6033
#define IDM_CLOSE_ALL_LUA               6034
#define IDM_TRACELOG                    6035
#define ID_LUA_CLEAR_RECENT             6036
#define IDM_LOAD_LATEST_LUA             6037
#define ID_LUA_RECENT                   6038
#define IDC_HOTKEYS_FLOWGROUP           6106
#define IDC_HOT_SCREENSHOT              6108
#define IDC_HOT_PAUSE                   6109
#define IDC_HOT_FASTFORWARD             6110
#define IDC_HOT_SPEEDDOWN               6111
#define IDC_HOT_FRAMEADVANCE            6112
#define IDC_HOT_SPEEDUP                 6113
#define IDC_HOT_READONLY                6114
#define IDC_HOT_PLAY                    6115
#define IDC_HOT_PLAYSTOP                6116
#define IDC_HOT_RECORD                  6117
#define IDC_HOT_RECORDSTOP              6118
#define IDC_FASTFORWARD                 6119
#define IDC_FRAMEADVANCE                6120
#define IDC_SPDUP                       6121
#define IDC_SPDDOWN                     6122
#define IDC_PAUSE                       6123
#define IDC_READONLY                    6124
#define IDC_SCREENSHOT                  6125
#define IDC_HOTKEYS_SAVEGROUP2          6129
#define IDC_CSAVE                       6143
#define IDC_CLOAD                       6144
#define IDC_1SEL                        6145
#define IDC_1SAVE                       6146
#define IDC_1LOAD                       6147
#define IDC_2SEL                        6148
#define IDC_2SAVE                       6149
#define IDC_2LOAD                       6150
#define IDC_3SEL                        6160
#define IDC_3SAVE                       6161
#define IDC_3LOAD                       6162
#define IDC_4SEL                        6163
#define IDC_4SAVE                       6164
#define IDC_4LOAD                       6165
#define IDC_5SEL                        6166
#define IDC_5SAVE                       6167
#define IDC_5LOAD                       6168
#define IDC_6SEL                        6169
#define IDC_6SAVE                       6170
#define IDC_6LOAD                       6171
#define IDC_7SEL                        6172
#define IDC_7SAVE                       6173
#define IDC_7LOAD                       6174
#define IDC_8SEL                        6175
#define IDC_8SAVE                       6176
#define IDC_8LOAD                       6177
#define IDC_9SEL                        6178
#define IDC_9SAVE                       6179
#define IDC_9LOAD                       6180
#define IDC_10SEL                       6181
#define IDC_10SAVE                      6182
#define IDC_10LOAD                      6183
#define IDC_PLAYMOVIE                   6184
#define IDC_STOPPLAY                    6185
#define IDC_RECORDMOVIE                 6186
#define IDC_STOPRECORD                  6187
#define IDC_SAVE                        6188
#define IDC_LOAD                        6189
#define IDC_SELECT                      6190
#define IDC_CURRENT                     6191
#define IDD_LANG_INFO                   7005
#define IDC_PAUSE_EMULATION_FOCUS       7007
#define IDC_FULLSCREEN_ON_LOADING       7008
#define IDC_START_EMU_ON_LOADING        7009
#define IDC_LANG_AUTHOR                 7024
#define IDC_LANG_VERSION                7025
#define IDC_LANG_DATE                   7026
#define IDC_LANG_AUTHOR_TEXT            7027
#define IDC_LANG_VERSION_TEXT           7028
#define IDC_LANG_DATE_TEXT              7029
#define IDC_CRC1CRC2                    7034
#define IDC_ROM_PLUGINS                 8005
#define IDC_SAVE_PROFILE                8006
#define IDD_MOVIE_PLAYBACK_DIALOG       9005
#define IDD_MOVIE_DIALOG                9005
#define ID_KAILLERA                     9105
#define ID_BENCHMARK                    9106
#define IDM_START_MOVIE_RECORDING       9205
#define IDM_START_MOVIE_PLAYBACK        9208
#define IDM_STOP_MOVIE                  9209
#define IDM_START_CAPTURE               9210
#define IDM_STOP_CAPTURE                9211
#define IDM_PLAY_LATEST_MOVIE           9212
#define IDM_LOOP_MOVIE                  9213
#define IDM_START_CAPTURE_PRESET        9214
#define IDC_CONTROLLER4                 9228
#define IDC_RSPPLUGIN2                  9229
#define IDC_CONTROLLER8                 9230
#define IDC_CONTROLLER1                 9252
#define IDC_CONTROLLER2                 9253
#define IDC_CONTROLLER3                 9254
#define IDC_GFXPLUGIN2                  9255
#define IDC_SOUNDPLUGIN2                9256
#define IDC_INPUTPLUGIN2                9257
#define IDC_CONTROLLER5                 9258
#define IDC_CONTROLLER6                 9259
#define IDC_CONTROLLER7                 9260
#define IDC_MOVIE_BROWSE                9305
#define IDC_MOVIE_REFRESH               9306
#define IDC_MOVIE_READONLY              9307
#define IDC_FROMSNAPSHOT_LABEL          9308
#define IDC_ROM_INFO_TEXT               9414
#define IDC_ROM_HEADER_INFO_TEXT2       9415
#define IDC_GROUP_START_FROM            9415
#define IDC_ROM_INFO_TEXT2              9416
#define IDC_GROUP_START_FROM2           9416
#define IDC_GROUP_START_FROM3           9418
#define IDC_MOVIE_AUTHOR_TEXT           9420
#define IDC_MOVIE_DESCRIPTION_TEXT      9421
#define IDC_ROM_INTERNAL_NAME_TEXT2     9424
#define IDC_ROM_COUNTRY_TEXT2           9425
#define IDC_MOVIE_VIDEO_TEXT            9426
#define IDC_MOVIE_SOUND_TEXT            9427
#define IDC_MOVIE_INPUT_TEXT            9428
#define IDC_MOVIE_RSP_TEXT              9429
#define IDC_ROM_CRC_TEXT                9430
#define IDC_ROM_CRC                     9431
#define IDC_MOVIE_CONTROLLER1_TEXT      9432
#define IDC_MOVIE_CONTROLLER2_TEXT      9433
#define IDC_MOVIE_CONTROLLER3_TEXT      9434
#define IDC_INI_MOVIEFILE_TEXT          9435
#define IDC_INI_AUTHOR                  9436
#define IDC_INI_DESCRIPTION             9437
#define IDC_INI_MOVIEFILE               9438
#define IDC_MOVIE_CONTROLLER4_TEXT      9439
#define IDC_ROM_INTERNAL_NAME2          9440
#define IDC_ROM_COUNTRY2                9441
#define IDC_ROM_CRC_TEXT2               9442
#define IDC_ROM_CRC3                    9443
#define IDC_MOVIE_VIDEO_TEXT2           9444
#define IDC_MOVIE_SOUND_TEXT2           9445
#define IDC_MOVIE_INPUT_TEXT2           9446
#define IDC_MOVIE_RSP_TEXT2             9447
#define IDC_MOVIE_CONTROLLER1_TEXT2     9448
#define IDC_MOVIE_CONTROLLER2_TEXT2     9449
#define IDC_MOVIE_CONTROLLER3_TEXT2     9450
#define IDC_MOVIE_CONTROLLER4_TEXT2     9451
#define IDC_MOVIE_LENGTH_TEXT           9452
#define IDC_MOVIE_FRAMES_TEXT           9453
#define IDC_MOVIE_RERECORDS_TEXT        9454
#define IDC_MOVIE_LENGTH                9455
#define IDC_MOVIE_FRAMES                9456
#define IDC_MOVIE_RERECORDS             9457
#define IDC_MOVIE_SNAPSHOT_TEXT         9458
#define IDC_FROMSNAPSHOT_TEXT           9458
#define IDC_MOVIE_CONTROLLERS           9506
#define IDC_ROM_PLUGINS2                9507
#define IDC_MOVIE_CONTROLLERS2          9508
#define IDC_STARTSFROM_LABEL            9509
#define IDC_FROMSNAPSHOT_RADIO          9510
#define IDC_FROMEXISTINGSNAPSHOT_RADIO  9511
#define IDC_FROMSTART_RADIO             9512
#define IDC_PAUSEAT_LABEL               9512
#define IDC_PAUSEAT_FIELD               9513
#define IDC_TEXTBOX_LUASCRIPTPATH       9514
#define IDC_TEXTBOX_LUACONSOLE          9515
#define IDC_BUTTON_LUASTATE             9516
#define IDC_BUTTON_LUAEDIT              9517
#define IDC_BUTTON_LUABROWSE            9518
#define IDC_BUTTON_LUACLEAR             9519
#define IDC_BUTTON_LUASTOP              9520
#define IDC_FROMEEPROM_RADIO            9521
#define IDC_TEXTBOX_LUAPROMPT           9525
#define IDC_ROUNDTOZERO                 10007
#define IDC_RECORD_RESETS               10008
#define IDC_FORCEINTERNAL               10009
#define IDC_EMULATEFLOATCRASHES         10011
#define IDC_ROMLIST                     12352
#define IDM_EXIT                        40001
#define IDM_RESET_ROM                   40007
#define IDC_STARTFROM2                  40008
#define IDC_GITREPO                     40011
#define IDM_RESET_RECENT_LUA            40013
#define IDM_FREEZE_RECENT_LUA           40014
#define IDD_OTHER_OPTIONS_DIALOG        40015
#define IDC_OTHEROPTIONS                40016
#define IDB_LOGO_BW                     40029
#define IDD_COREDBG                     40031
#define IDC_COREDBG_GROUPBOX            40032
#define IDC_COREDBG_TOGGLEPAUSE         40033
#define IDC_COREDBG_INSTRUCTION         40035
#define IDC_COREDBG_RSP                 40037
#define IDC_COREDBG_RSP_TOGGLE          40038
#define IDM_COREDBG                     40039
#define IDC_COREDBG_RSP_TOGGLE2         40039
#define IDB_PAUSE                       40040
#define IDB_RESUME                      40041
#define IDC_COREDBG_INSTDECODEMODE      40042
#define IDC_COREDBG_PRECOMPADDR         40043
#define IDC_COREDBG_PRECOMPOP           40044
#define IDC_COREDBG_STEP                40045
#define IDC_COREDBG_VI                  40046
#define IDC_COREDBG_DUMPRDRAM           40046
#define IDC_COREDBG_DISASSEMBLED        40046
#define IDC_COREDBG_CART_TILT           40047
#define IDC_AV_NOSYNC                   40050
#define IDC_AV_AUDIOSYNC                40051
#define IDC_AV_VIDEOSYNC                40052
#define IDM_LOAD_LATEST_ROM             40053
#define IDC_LAG_EMULATION               40054
#define IDC_CLOCK_SPD_MULT              40055
#define IDC_COMBO_CLOCK_SPD_MULT        40056
#define IDC_CLOCK_SPD_MULT_TEXT         40057
#define IDD_MUPENERROR                  40058
#define IDC_ERROR_PANIC_IGNORE          40059
#define IDC_ERROR_PANIC_CLOSE           40060
#define IDC_CRASHREPORT                 40061
#define IDC_ERRORTEXT                   40062
#define IDC_ERROR_PICTUREBOX            40063
#define IDD_NEW_HOTKEY_DIALOG           40064
#define IDM_SEEKER                      40065
#define IDM_FASTFORWARD_ON              40066
#define IDM_FASTFORWARD_OFF             40067
#define IDC_STATUSBARZEROINDEX          40068
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
